- name: Run martinkukolos/action-ftp-deployment@v1
    uses: martinkukolos/action-ftp-deployment@v1
    with:
      ftp-server: '216.246.47.8'
      ftp-user: 'github@javascript.dannieldev.com'
      ftp-password: 'DEwgWB0v7yv@f'
      source-folder: './'
